(define (domain transport)
    (:predicates (car ?c) (box ?b) (place ?p) (full ?c) (empty ?c) 
        (at ?obj ?p))
        
    (:action load
     :parameters (?box ?car ?place)
     :precondition (and (box ?box)
                        (car ?car)
                        (place ?place)
                        (empty ?car)
                        (at ?box ?place)
                        (at ?car ?place))
     :effect (and (at ?box ?car)
                  (full ?car)
                  (not (at ?box ?place))
                  (not (empty ?car)))
    )

    (:action unload
     :parameters (?box ?car ?place)
     :precondition (and (box ?box)
                        (car ?car)
                        (place ?place)
                        (full ?car)
                        (at ?car ?place)
                        (at ?box ?car))
     :effect (and (at ?box ?place)
                  (empty ?car)
                  (not (full ?car))
                  (not (at ?box ?car)))
    )
    
    (:action move
     :parameters (?car ?from ?to)
     :precondition (and (car ?car)
                        (place ?from)
                        (place ?to)
                        (at ?car ?from))
     :effect (and (at ?car ?to)
                  (not (at ?car ?from)))
    )
)